In [1271]:
import pandas as pd
import numpy as np

In [1272]:
df=pd.read_excel("Ecommerce_Unclean_Project.xlsx")

In [1273]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,17-02-2025,Rahul,rahul71@gmail.com,9.789375e+09,Lucknow,UP,Mouse,Electronics,4.0,9999.0,NaN,Card,Returned,27-02-2025
520,ORD1609,2025/03/21,Rahul,rahul99@gmail.com,9.552650e+09,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,,Wallet,Pending,28-03-2025
521,ORD1610,10-04-2025,Rohit,rohit96@gmail.com,9.700117e+09,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,,NetBanking,Delivered,16-04-2025
522,ORD1611,11-01-2025,Neha,neha22@gmail.com,9.580304e+09,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,,COD,Pending,16-01-2025
523,ORD1612,03-03-2025,Vikas,vikas46@gmail.com,9.551158e+09,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5,COD,Cancelled,09-03-2025

In [1274]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     0
Email             0
Phone            22
City              0
State             0
Product           0
Category          0
Qty              67
Unit_Price       53
Discount         69
Payment_Mode      0
Order_Status      0
Delivery_Date    21
dtype: int64

In [1275]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       524 non-null    str
 1   Order_Date     524 non-null    str
 2   Customer_Name  524 non-null    str
 3   Email          524 non-null    str
 4   Phone          502 non-null    float64
 5   City           524 non-null    str
 6   State          524 non-null    str
 7   Product        524 non-null    str
 8   Category       524 non-null    str
 9   Qty            457 non-null    float64
 10  Unit_Price     471 non-null    float64
 11  Discount       455 non-null    object
 12  Payment_Mode   524 non-null    str
 13  Order_Status   524 non-null    str
 14  Delivery_Date  503 non-null    str
dtypes: float64(3), object(1), str(11)
memory usage: 61.5+ KB

In [1276]:
df=df.drop_duplicates()

In [1277]:
df.info()

<class 'pandas.DataFrame'>
Index: 513 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       513 non-null    str
 1   Order_Date     513 non-null    str
 2   Customer_Name  513 non-null    str
 3   Email          513 non-null    str
 4   Phone          491 non-null    float64
 5   City           513 non-null    str
 6   State          513 non-null    str
 7   Product        513 non-null    str
 8   Category       513 non-null    str
 9   Qty            448 non-null    float64
 10  Unit_Price     462 non-null    float64
 11  Discount       446 non-null    object
 12  Payment_Mode   513 non-null    str
 13  Order_Status   513 non-null    str
 14  Delivery_Date  492 non-null    str
dtypes: float64(3), object(1), str(11)
memory usage: 64.1+ KB

In [1278]:
df["Phone"]=df["Phone"].astype("Int64")

In [1279]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9829008196,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9280491167,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9943310925,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9495120474,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9237331620,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,17-02-2025,Rahul,rahul71@gmail.com,9789375429,Lucknow,UP,Mouse,Electronics,4.0,9999.0,NaN,Card,Returned,27-02-2025
520,ORD1609,2025/03/21,Rahul,rahul99@gmail.com,9552649559,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,,Wallet,Pending,28-03-2025
521,ORD1610,10-04-2025,Rohit,rohit96@gmail.com,9700116928,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,,NetBanking,Delivered,16-04-2025
522,ORD1611,11-01-2025,Neha,neha22@gmail.com,9580304152,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,,COD,Pending,16-01-2025
523,ORD1612,03-03-2025,Vikas,vikas46@gmail.com,9551158398,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5,COD,Cancelled,09-03-2025

In [1280]:
df["Phone"].dtype

Int64Dtype()

In [1281]:
df["Phone"]=df["Phone"].astype("string")        # string me is liye badla kyu ki phone number int hoga to use add kar sakte hain par string me add nahi ho sakta wo pura number ek mana jayega

In [1282]:
df["Phone"].dtype

In [1283]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9829008196,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9280491167,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9943310925,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9495120474,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9237331620,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,17-02-2025,Rahul,rahul71@gmail.com,9789375429,Lucknow,UP,Mouse,Electronics,4.0,9999.0,NaN,Card,Returned,27-02-2025
520,ORD1609,2025/03/21,Rahul,rahul99@gmail.com,9552649559,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,,Wallet,Pending,28-03-2025
521,ORD1610,10-04-2025,Rohit,rohit96@gmail.com,9700116928,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,,NetBanking,Delivered,16-04-2025
522,ORD1611,11-01-2025,Neha,neha22@gmail.com,9580304152,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,,COD,Pending,16-01-2025
523,ORD1612,03-03-2025,Vikas,vikas46@gmail.com,9551158398,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5,COD,Cancelled,09-03-2025

In [1284]:
df.info()

<class 'pandas.DataFrame'>
Index: 513 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       513 non-null    str
 1   Order_Date     513 non-null    str
 2   Customer_Name  513 non-null    str
 3   Email          513 non-null    str
 4   Phone          491 non-null    string
 5   City           513 non-null    str
 6   State          513 non-null    str
 7   Product        513 non-null    str
 8   Category       513 non-null    str
 9   Qty            448 non-null    float64
 10  Unit_Price     462 non-null    float64
 11  Discount       446 non-null    object
 12  Payment_Mode   513 non-null    str
 13  Order_Status   513 non-null    str
 14  Delivery_Date  492 non-null    str
dtypes: float64(2), object(1), str(11), string(1)
memory usage: 64.1+ KB

In [1285]:
df["Phone"]=df["Phone"].fillna("0000000000")

In [1286]:
df.info()

<class 'pandas.DataFrame'>
Index: 513 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       513 non-null    str
 1   Order_Date     513 non-null    str
 2   Customer_Name  513 non-null    str
 3   Email          513 non-null    str
 4   Phone          513 non-null    string
 5   City           513 non-null    str
 6   State          513 non-null    str
 7   Product        513 non-null    str
 8   Category       513 non-null    str
 9   Qty            448 non-null    float64
 10  Unit_Price     462 non-null    float64
 11  Discount       446 non-null    object
 12  Payment_Mode   513 non-null    str
 13  Order_Status   513 non-null    str
 14  Delivery_Date  492 non-null    str
dtypes: float64(2), object(1), str(11), string(1)
memory usage: 64.1+ KB

In [1287]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9829008196,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9280491167,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9943310925,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9495120474,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9237331620,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025

In [1288]:
df["Qty"]=pd.to_numeric(df["Qty"], errors="coerce")         # Qty ko numeric kar dia or NaN ya null values ko errors="coerce" NaN kar dega

In [1289]:
df["Qty"]=df["Qty"].fillna(0)

In [1290]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9829008196,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9280491167,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9943310925,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9495120474,Bengaluru,Karnataka,Laptop,Electronics,0.0,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9237331620,Pune,Maharashtra,Bottle,Home,0.0,1999.0,,Wallet,Cancelled,07-04-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,17-02-2025,Rahul,rahul71@gmail.com,9789375429,Lucknow,UP,Mouse,Electronics,4.0,9999.0,NaN,Card,Returned,27-02-2025
520,ORD1609,2025/03/21,Rahul,rahul99@gmail.com,9552649559,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,,Wallet,Pending,28-03-2025
521,ORD1610,10-04-2025,Rohit,rohit96@gmail.com,9700116928,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,,NetBanking,Delivered,16-04-2025
522,ORD1611,11-01-2025,Neha,neha22@gmail.com,9580304152,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,,COD,Pending,16-01-2025
523,ORD1612,03-03-2025,Vikas,vikas46@gmail.com,9551158398,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5,COD,Cancelled,09-03-2025

In [1291]:
df["Qty"]=df["Qty"].astype("Int64")

In [1292]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9829008196,Delhi,Delhi,Chair,Furniture,4,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9280491167,Pune,Maharashtra,Watch,Fashion,5,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9943310925,Jaipur,Rajasthan,Mouse,Electronics,3,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9495120474,Bengaluru,Karnataka,Laptop,Electronics,0,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9237331620,Pune,Maharashtra,Bottle,Home,0,1999.0,,Wallet,Cancelled,07-04-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,17-02-2025,Rahul,rahul71@gmail.com,9789375429,Lucknow,UP,Mouse,Electronics,4,9999.0,NaN,Card,Returned,27-02-2025
520,ORD1609,2025/03/21,Rahul,rahul99@gmail.com,9552649559,Mumbai,Maharashtra,Bottle,Home,2,1499.0,,Wallet,Pending,28-03-2025
521,ORD1610,10-04-2025,Rohit,rohit96@gmail.com,9700116928,Jaipur,Rajasthan,Mouse,Electronics,1,NaN,,NetBanking,Delivered,16-04-2025
522,ORD1611,11-01-2025,Neha,neha22@gmail.com,9580304152,Jaipur,Rajasthan,Chair,Furniture,3,999.0,,COD,Pending,16-01-2025
523,ORD1612,03-03-2025,Vikas,vikas46@gmail.com,9551158398,Jaipur,Rajasthan,Shoes,Fashion,3,999.0,5,COD,Cancelled,09-03-2025

In [1293]:
df.info()

<class 'pandas.DataFrame'>
Index: 513 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       513 non-null    str
 1   Order_Date     513 non-null    str
 2   Customer_Name  513 non-null    str
 3   Email          513 non-null    str
 4   Phone          513 non-null    string
 5   City           513 non-null    str
 6   State          513 non-null    str
 7   Product        513 non-null    str
 8   Category       513 non-null    str
 9   Qty            513 non-null    Int64
 10  Unit_Price     462 non-null    float64
 11  Discount       446 non-null    object
 12  Payment_Mode   513 non-null    str
 13  Order_Status   513 non-null    str
 14  Delivery_Date  492 non-null    str
dtypes: Int64(1), float64(1), object(1), str(11), string(1)
memory usage: 64.6+ KB

In [1294]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9829008196,Delhi,Delhi,Chair,Furniture,4,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9280491167,Pune,Maharashtra,Watch,Fashion,5,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9943310925,Jaipur,Rajasthan,Mouse,Electronics,3,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9495120474,Bengaluru,Karnataka,Laptop,Electronics,0,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9237331620,Pune,Maharashtra,Bottle,Home,0,1999.0,,Wallet,Cancelled,07-04-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,17-02-2025,Rahul,rahul71@gmail.com,9789375429,Lucknow,UP,Mouse,Electronics,4,9999.0,NaN,Card,Returned,27-02-2025
520,ORD1609,2025/03/21,Rahul,rahul99@gmail.com,9552649559,Mumbai,Maharashtra,Bottle,Home,2,1499.0,,Wallet,Pending,28-03-2025
521,ORD1610,10-04-2025,Rohit,rohit96@gmail.com,9700116928,Jaipur,Rajasthan,Mouse,Electronics,1,NaN,,NetBanking,Delivered,16-04-2025
522,ORD1611,11-01-2025,Neha,neha22@gmail.com,9580304152,Jaipur,Rajasthan,Chair,Furniture,3,999.0,,COD,Pending,16-01-2025
523,ORD1612,03-03-2025,Vikas,vikas46@gmail.com,9551158398,Jaipur,Rajasthan,Shoes,Fashion,3,999.0,5,COD,Cancelled,09-03-2025

In [1295]:
df["Unit_Price"]=pd.to_numeric(df["Unit_Price"], errors="coerce")

In [1296]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9829008196,Delhi,Delhi,Chair,Furniture,4,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9280491167,Pune,Maharashtra,Watch,Fashion,5,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9943310925,Jaipur,Rajasthan,Mouse,Electronics,3,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9495120474,Bengaluru,Karnataka,Laptop,Electronics,0,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9237331620,Pune,Maharashtra,Bottle,Home,0,1999.0,,Wallet,Cancelled,07-04-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,17-02-2025,Rahul,rahul71@gmail.com,9789375429,Lucknow,UP,Mouse,Electronics,4,9999.0,NaN,Card,Returned,27-02-2025
520,ORD1609,2025/03/21,Rahul,rahul99@gmail.com,9552649559,Mumbai,Maharashtra,Bottle,Home,2,1499.0,,Wallet,Pending,28-03-2025
521,ORD1610,10-04-2025,Rohit,rohit96@gmail.com,9700116928,Jaipur,Rajasthan,Mouse,Electronics,1,NaN,,NetBanking,Delivered,16-04-2025
522,ORD1611,11-01-2025,Neha,neha22@gmail.com,9580304152,Jaipur,Rajasthan,Chair,Furniture,3,999.0,,COD,Pending,16-01-2025
523,ORD1612,03-03-2025,Vikas,vikas46@gmail.com,9551158398,Jaipur,Rajasthan,Shoes,Fashion,3,999.0,5,COD,Cancelled,09-03-2025

In [1297]:
df["Discount"]=pd.to_numeric(df["Discount"], errors="coerce")

In [1298]:
df["Discount"]=df["Discount"].fillna(0)

In [1299]:
df["Discount"]=df["Discount"].astype("Int64")

In [1300]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9829008196,Delhi,Delhi,Chair,Furniture,4,1999.0,0,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9280491167,Pune,Maharashtra,Watch,Fashion,5,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9943310925,Jaipur,Rajasthan,Mouse,Electronics,3,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9495120474,Bengaluru,Karnataka,Laptop,Electronics,0,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9237331620,Pune,Maharashtra,Bottle,Home,0,1999.0,0,Wallet,Cancelled,07-04-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,17-02-2025,Rahul,rahul71@gmail.com,9789375429,Lucknow,UP,Mouse,Electronics,4,9999.0,0,Card,Returned,27-02-2025
520,ORD1609,2025/03/21,Rahul,rahul99@gmail.com,9552649559,Mumbai,Maharashtra,Bottle,Home,2,1499.0,0,Wallet,Pending,28-03-2025
521,ORD1610,10-04-2025,Rohit,rohit96@gmail.com,9700116928,Jaipur,Rajasthan,Mouse,Electronics,1,NaN,0,NetBanking,Delivered,16-04-2025
522,ORD1611,11-01-2025,Neha,neha22@gmail.com,9580304152,Jaipur,Rajasthan,Chair,Furniture,3,999.0,0,COD,Pending,16-01-2025
523,ORD1612,03-03-2025,Vikas,vikas46@gmail.com,9551158398,Jaipur,Rajasthan,Shoes,Fashion,3,999.0,5,COD,Cancelled,09-03-2025

In [1301]:
df.info()

<class 'pandas.DataFrame'>
Index: 513 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       513 non-null    str
 1   Order_Date     513 non-null    str
 2   Customer_Name  513 non-null    str
 3   Email          513 non-null    str
 4   Phone          513 non-null    string
 5   City           513 non-null    str
 6   State          513 non-null    str
 7   Product        513 non-null    str
 8   Category       513 non-null    str
 9   Qty            513 non-null    Int64
 10  Unit_Price     462 non-null    float64
 11  Discount       513 non-null    Int64
 12  Payment_Mode   513 non-null    str
 13  Order_Status   513 non-null    str
 14  Delivery_Date  492 non-null    str
dtypes: Int64(2), float64(1), str(11), string(1)
memory usage: 65.1 KB

In [1302]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     0
Email             0
Phone             0
City              0
State             0
Product           0
Category          0
Qty               0
Unit_Price       51
Discount          0
Payment_Mode      0
Order_Status      0
Delivery_Date    21
dtype: int64

In [1303]:
df["Order_Date"]=pd.to_datetime(df["Order_Date"], format="mixed", dayfirst=True, errors="coerce")

In [1304]:
print(df.loc[pd.to_datetime(df["Order_Date"], errors="coerce").isna(), "Order_Date"])

38    NaT
78    NaT
118   NaT
158   NaT
198   NaT
238   NaT
278   NaT
318   NaT
358   NaT
398   NaT
438   NaT
478   NaT
Name: Order_Date, dtype: datetime64[us]

In [1305]:
print(df.loc[[38, 78, 118, 158, 198, 238, 278, 318, 358, 398, 438, 478],
    "Order_Date"])

38    NaT
78    NaT
118   NaT
158   NaT
198   NaT
238   NaT
278   NaT
318   NaT
358   NaT
398   NaT
438   NaT
478   NaT
Name: Order_Date, dtype: datetime64[us]

In [1306]:
df.info()

<class 'pandas.DataFrame'>
Index: 513 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       513 non-null    str
 1   Order_Date     501 non-null    datetime64[us]
 2   Customer_Name  513 non-null    str
 3   Email          513 non-null    str
 4   Phone          513 non-null    string
 5   City           513 non-null    str
 6   State          513 non-null    str
 7   Product        513 non-null    str
 8   Category       513 non-null    str
 9   Qty            513 non-null    Int64
 10  Unit_Price     462 non-null    float64
 11  Discount       513 non-null    Int64
 12  Payment_Mode   513 non-null    str
 13  Order_Status   513 non-null    str
 14  Delivery_Date  492 non-null    str
dtypes: Int64(2), datetime64[us](1), float64(1), str(10), string(1)
memory usage: 81.3 KB

In [1307]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196,Delhi,Delhi,Chair,Furniture,4,1999.0,0,UPI,Pending,03-07-2025
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167,Pune,Maharashtra,Watch,Fashion,5,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925,Jaipur,Rajasthan,Mouse,Electronics,3,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,2025-01-20,Vikas,vikas51@gmail.com,9495120474,Bengaluru,Karnataka,Laptop,Electronics,0,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,2025-04-02,Rohit,rohit71@gmail.com,9237331620,Pune,Maharashtra,Bottle,Home,0,1999.0,0,Wallet,Cancelled,07-04-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2025-02-17,Rahul,rahul71@gmail.com,9789375429,Lucknow,UP,Mouse,Electronics,4,9999.0,0,Card,Returned,27-02-2025
520,ORD1609,2025-03-21,Rahul,rahul99@gmail.com,9552649559,Mumbai,Maharashtra,Bottle,Home,2,1499.0,0,Wallet,Pending,28-03-2025
521,ORD1610,2025-04-10,Rohit,rohit96@gmail.com,9700116928,Jaipur,Rajasthan,Mouse,Electronics,1,NaN,0,NetBanking,Delivered,16-04-2025
522,ORD1611,2025-01-11,Neha,neha22@gmail.com,9580304152,Jaipur,Rajasthan,Chair,Furniture,3,999.0,0,COD,Pending,16-01-2025
523,ORD1612,2025-03-03,Vikas,vikas46@gmail.com,9551158398,Jaipur,Rajasthan,Shoes,Fashion,3,999.0,5,COD,Cancelled,09-03-2025

In [1308]:
df["Delivery_Date"]=pd.to_datetime(df["Delivery_Date"], format = "mixed", dayfirst=True, errors="coerce")

In [1309]:
df["Delivery_Date"]=df["Delivery_Date"].fillna(df["Order_Date"])

In [1310]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196,Delhi,Delhi,Chair,Furniture,4,1999.0,0,UPI,Pending,2025-07-03
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167,Pune,Maharashtra,Watch,Fashion,5,4999.0,20,Card,Pending,2025-02-09
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925,Jaipur,Rajasthan,Mouse,Electronics,3,1999.0,5,COD,Returned,2025-05-08
3,ORD1005,2025-01-20,Vikas,vikas51@gmail.com,9495120474,Bengaluru,Karnataka,Laptop,Electronics,0,NaN,15,Wallet,Pending,2025-01-27
4,ORD1006,2025-04-02,Rohit,rohit71@gmail.com,9237331620,Pune,Maharashtra,Bottle,Home,0,1999.0,0,Wallet,Cancelled,2025-04-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2025-02-17,Rahul,rahul71@gmail.com,9789375429,Lucknow,UP,Mouse,Electronics,4,9999.0,0,Card,Returned,2025-02-27
520,ORD1609,2025-03-21,Rahul,rahul99@gmail.com,9552649559,Mumbai,Maharashtra,Bottle,Home,2,1499.0,0,Wallet,Pending,2025-03-28
521,ORD1610,2025-04-10,Rohit,rohit96@gmail.com,9700116928,Jaipur,Rajasthan,Mouse,Electronics,1,NaN,0,NetBanking,Delivered,2025-04-16
522,ORD1611,2025-01-11,Neha,neha22@gmail.com,9580304152,Jaipur,Rajasthan,Chair,Furniture,3,999.0,0,COD,Pending,2025-01-16
523,ORD1612,2025-03-03,Vikas,vikas46@gmail.com,9551158398,Jaipur,Rajasthan,Shoes,Fashion,3,999.0,5,COD,Cancelled,2025-03-09

In [1311]:
df.info()

<class 'pandas.DataFrame'>
Index: 513 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       513 non-null    str
 1   Order_Date     501 non-null    datetime64[us]
 2   Customer_Name  513 non-null    str
 3   Email          513 non-null    str
 4   Phone          513 non-null    string
 5   City           513 non-null    str
 6   State          513 non-null    str
 7   Product        513 non-null    str
 8   Category       513 non-null    str
 9   Qty            513 non-null    Int64
 10  Unit_Price     462 non-null    float64
 11  Discount       513 non-null    Int64
 12  Payment_Mode   513 non-null    str
 13  Order_Status   513 non-null    str
 14  Delivery_Date  511 non-null    datetime64[us]
dtypes: Int64(2), datetime64[us](2), float64(1), str(9), string(1)
memory usage: 81.3 KB

In [1312]:
df.isnull().sum()

Order_ID          0
Order_Date       12
Customer_Name     0
Email             0
Phone             0
City              0
State             0
Product           0
Category          0
Qty               0
Unit_Price       51
Discount          0
Payment_Mode      0
Order_Status      0
Delivery_Date     2
dtype: int64

In [1313]:
# Remove extra spaces

df=df.apply(lambda x:x.str.strip().str.title() if x.dtype=="str" else x)

In [1314]:
df["City"].unique()

<StringArray>
['Delhi', 'Pune', 'Jaipur', 'Bengaluru', 'Mumbai', 'Lucknow']
Length: 6, dtype: str

In [1315]:
df["State"].unique()

<StringArray>
['Delhi', 'Maharashtra', 'Rajasthan', 'Karnataka', 'Up']
Length: 5, dtype: str

In [1316]:
df["Category"].unique()

<StringArray>
['Furniture', 'Fashion', 'Electronics', 'Home']
Length: 4, dtype: str

In [1317]:
df.describe()

,Order_Date,Qty,Unit_Price,Discount,Delivery_Date
count,501,513.0,462.000000,513.0,511
mean,2025-04-08 18:00:43.113772,2.440546,3176.272727,7.768031,2025-04-09 20:54:00.704501
min,2025-01-01 00:00:00,-1.0,499.000000,0.0,2025-01-04 00:00:00
25%,2025-02-18 00:00:00,1.0,999.000000,0.0,2025-02-24 12:00:00
50%,2025-04-07 00:00:00,3.0,1999.000000,5.0,2025-04-11 00:00:00
75%,2025-05-21 00:00:00,4.0,4999.000000,15.0,2025-05-24 12:00:00
max,2025-12-03 00:00:00,5.0,9999.000000,20.0,2025-07-08 00:00:00
std,NaN,2.06838,2971.838671,7.777345,NaN

In [1318]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,Ord1002,2025-06-30,Neha,Neha82@Gmail.Com,9829008196,Delhi,Delhi,Chair,Furniture,4,1999.0,0,Upi,Pending,2025-07-03
1,Ord1003,2025-02-03,Rohit,Rohit45@Gmail.Com,9280491167,Pune,Maharashtra,Watch,Fashion,5,4999.0,20,Card,Pending,2025-02-09
2,Ord1004,2025-05-06,Amit,Amit6@Gmail.Com,9943310925,Jaipur,Rajasthan,Mouse,Electronics,3,1999.0,5,Cod,Returned,2025-05-08
3,Ord1005,2025-01-20,Vikas,Vikas51@Gmail.Com,9495120474,Bengaluru,Karnataka,Laptop,Electronics,0,NaN,15,Wallet,Pending,2025-01-27
4,Ord1006,2025-04-02,Rohit,Rohit71@Gmail.Com,9237331620,Pune,Maharashtra,Bottle,Home,0,1999.0,0,Wallet,Cancelled,2025-04-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,Ord1608,2025-02-17,Rahul,Rahul71@Gmail.Com,9789375429,Lucknow,Up,Mouse,Electronics,4,9999.0,0,Card,Returned,2025-02-27
520,Ord1609,2025-03-21,Rahul,Rahul99@Gmail.Com,9552649559,Mumbai,Maharashtra,Bottle,Home,2,1499.0,0,Wallet,Pending,2025-03-28
521,Ord1610,2025-04-10,Rohit,Rohit96@Gmail.Com,9700116928,Jaipur,Rajasthan,Mouse,Electronics,1,NaN,0,Netbanking,Delivered,2025-04-16
522,Ord1611,2025-01-11,Neha,Neha22@Gmail.Com,9580304152,Jaipur,Rajasthan,Chair,Furniture,3,999.0,0,Cod,Pending,2025-01-16
523,Ord1612,2025-03-03,Vikas,Vikas46@Gmail.Com,9551158398,Jaipur,Rajasthan,Shoes,Fashion,3,999.0,5,Cod,Cancelled,2025-03-09

In [1319]:
df=df[df["Qty"]>=0]

In [1320]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,Ord1002,2025-06-30,Neha,Neha82@Gmail.Com,9829008196,Delhi,Delhi,Chair,Furniture,4,1999.0,0,Upi,Pending,2025-07-03
1,Ord1003,2025-02-03,Rohit,Rohit45@Gmail.Com,9280491167,Pune,Maharashtra,Watch,Fashion,5,4999.0,20,Card,Pending,2025-02-09
2,Ord1004,2025-05-06,Amit,Amit6@Gmail.Com,9943310925,Jaipur,Rajasthan,Mouse,Electronics,3,1999.0,5,Cod,Returned,2025-05-08
3,Ord1005,2025-01-20,Vikas,Vikas51@Gmail.Com,9495120474,Bengaluru,Karnataka,Laptop,Electronics,0,NaN,15,Wallet,Pending,2025-01-27
4,Ord1006,2025-04-02,Rohit,Rohit71@Gmail.Com,9237331620,Pune,Maharashtra,Bottle,Home,0,1999.0,0,Wallet,Cancelled,2025-04-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,Ord1608,2025-02-17,Rahul,Rahul71@Gmail.Com,9789375429,Lucknow,Up,Mouse,Electronics,4,9999.0,0,Card,Returned,2025-02-27
520,Ord1609,2025-03-21,Rahul,Rahul99@Gmail.Com,9552649559,Mumbai,Maharashtra,Bottle,Home,2,1499.0,0,Wallet,Pending,2025-03-28
521,Ord1610,2025-04-10,Rohit,Rohit96@Gmail.Com,9700116928,Jaipur,Rajasthan,Mouse,Electronics,1,NaN,0,Netbanking,Delivered,2025-04-16
522,Ord1611,2025-01-11,Neha,Neha22@Gmail.Com,9580304152,Jaipur,Rajasthan,Chair,Furniture,3,999.0,0,Cod,Pending,2025-01-16
523,Ord1612,2025-03-03,Vikas,Vikas46@Gmail.Com,9551158398,Jaipur,Rajasthan,Shoes,Fashion,3,999.0,5,Cod,Cancelled,2025-03-09

In [1321]:
df.describe()

,Order_Date,Qty,Unit_Price,Discount,Delivery_Date
count,446,458.0,411.000000,458.0,456
mean,2025-04-07 13:23:56.771300,2.853712,3258.367397,7.816594,2025-04-09 21:22:06.315789
min,2025-01-01 00:00:00,0.0,499.000000,0.0,2025-01-04 00:00:00
25%,2025-02-17 00:00:00,1.0,999.000000,0.0,2025-02-23 00:00:00
50%,2025-04-07 00:00:00,3.0,1999.000000,5.0,2025-04-13 00:00:00
75%,2025-05-20 00:00:00,5.0,4999.000000,15.0,2025-05-25 00:00:00
max,2025-12-03 00:00:00,5.0,9999.000000,20.0,2025-07-08 00:00:00
std,NaN,1.788119,3048.514807,7.850712,NaN

In [1322]:
# Validate email address

df=df[df["Email"].str.contains('@', na=False)]

In [1323]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,Ord1002,2025-06-30,Neha,Neha82@Gmail.Com,9829008196,Delhi,Delhi,Chair,Furniture,4,1999.0,0,Upi,Pending,2025-07-03
1,Ord1003,2025-02-03,Rohit,Rohit45@Gmail.Com,9280491167,Pune,Maharashtra,Watch,Fashion,5,4999.0,20,Card,Pending,2025-02-09
2,Ord1004,2025-05-06,Amit,Amit6@Gmail.Com,9943310925,Jaipur,Rajasthan,Mouse,Electronics,3,1999.0,5,Cod,Returned,2025-05-08
3,Ord1005,2025-01-20,Vikas,Vikas51@Gmail.Com,9495120474,Bengaluru,Karnataka,Laptop,Electronics,0,NaN,15,Wallet,Pending,2025-01-27
4,Ord1006,2025-04-02,Rohit,Rohit71@Gmail.Com,9237331620,Pune,Maharashtra,Bottle,Home,0,1999.0,0,Wallet,Cancelled,2025-04-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,Ord1608,2025-02-17,Rahul,Rahul71@Gmail.Com,9789375429,Lucknow,Up,Mouse,Electronics,4,9999.0,0,Card,Returned,2025-02-27
520,Ord1609,2025-03-21,Rahul,Rahul99@Gmail.Com,9552649559,Mumbai,Maharashtra,Bottle,Home,2,1499.0,0,Wallet,Pending,2025-03-28
521,Ord1610,2025-04-10,Rohit,Rohit96@Gmail.Com,9700116928,Jaipur,Rajasthan,Mouse,Electronics,1,NaN,0,Netbanking,Delivered,2025-04-16
522,Ord1611,2025-01-11,Neha,Neha22@Gmail.Com,9580304152,Jaipur,Rajasthan,Chair,Furniture,3,999.0,0,Cod,Pending,2025-01-16
523,Ord1612,2025-03-03,Vikas,Vikas46@Gmail.Com,9551158398,Jaipur,Rajasthan,Shoes,Fashion,3,999.0,5,Cod,Cancelled,2025-03-09

In [1324]:
df.isnull().sum()

Order_ID          0
Order_Date       12
Customer_Name     0
Email             0
Phone             0
City              0
State             0
Product           0
Category          0
Qty               0
Unit_Price       46
Discount          0
Payment_Mode      0
Order_Status      0
Delivery_Date     2
dtype: int64

# Feature Engineering

In [1325]:
# Total Sales

df["Total_Sales"]=df["Qty"]*df["Unit_Price"]

In [1326]:
df["Total_Sales"]=df["Total_Sales"].round(2)

In [1327]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Total_Sales
0,Ord1002,2025-06-30,Neha,Neha82@Gmail.Com,9829008196,Delhi,Delhi,Chair,Furniture,4,1999.0,0,Upi,Pending,2025-07-03,7996.0
1,Ord1003,2025-02-03,Rohit,Rohit45@Gmail.Com,9280491167,Pune,Maharashtra,Watch,Fashion,5,4999.0,20,Card,Pending,2025-02-09,24995.0
2,Ord1004,2025-05-06,Amit,Amit6@Gmail.Com,9943310925,Jaipur,Rajasthan,Mouse,Electronics,3,1999.0,5,Cod,Returned,2025-05-08,5997.0
3,Ord1005,2025-01-20,Vikas,Vikas51@Gmail.Com,9495120474,Bengaluru,Karnataka,Laptop,Electronics,0,NaN,15,Wallet,Pending,2025-01-27,<NA>
4,Ord1006,2025-04-02,Rohit,Rohit71@Gmail.Com,9237331620,Pune,Maharashtra,Bottle,Home,0,1999.0,0,Wallet,Cancelled,2025-04-07,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,Ord1608,2025-02-17,Rahul,Rahul71@Gmail.Com,9789375429,Lucknow,Up,Mouse,Electronics,4,9999.0,0,Card,Returned,2025-02-27,39996.0
520,Ord1609,2025-03-21,Rahul,Rahul99@Gmail.Com,9552649559,Mumbai,Maharashtra,Bottle,Home,2,1499.0,0,Wallet,Pending,2025-03-28,2998.0
521,Ord1610,2025-04-10,Rohit,Rohit96@Gmail.Com,9700116928,Jaipur,Rajasthan,Mouse,Electronics,1,NaN,0,Netbanking,Delivered,2025-04-16,<NA>
522,Ord1611,2025-01-11,Neha,Neha22@Gmail.Com,9580304152,Jaipur,Rajasthan,Chair,Furniture,3,999.0,0,Cod,Pending,2025-01-16,2997.0
523,Ord1612,2025-03-03,Vikas,Vikas46@Gmail.Com,9551158398,Jaipur,Rajasthan,Shoes,Fashion,3,999.0,5,Cod,Cancelled,2025-03-09,2997.0

In [1328]:
# Net Amount

df["Net_Amount"]=df["Total_Sales"]-(df["Total_Sales"]*df["Discount"]/100)

In [1329]:
df["Net_Amount"]=df["Net_Amount"].round(2)

In [1330]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Total_Sales,Net_Amount
0,Ord1002,2025-06-30,Neha,Neha82@Gmail.Com,9829008196,Delhi,Delhi,Chair,Furniture,4,1999.0,0,Upi,Pending,2025-07-03,7996.0,7996.0
1,Ord1003,2025-02-03,Rohit,Rohit45@Gmail.Com,9280491167,Pune,Maharashtra,Watch,Fashion,5,4999.0,20,Card,Pending,2025-02-09,24995.0,19996.0
2,Ord1004,2025-05-06,Amit,Amit6@Gmail.Com,9943310925,Jaipur,Rajasthan,Mouse,Electronics,3,1999.0,5,Cod,Returned,2025-05-08,5997.0,5697.15
3,Ord1005,2025-01-20,Vikas,Vikas51@Gmail.Com,9495120474,Bengaluru,Karnataka,Laptop,Electronics,0,NaN,15,Wallet,Pending,2025-01-27,<NA>,<NA>
4,Ord1006,2025-04-02,Rohit,Rohit71@Gmail.Com,9237331620,Pune,Maharashtra,Bottle,Home,0,1999.0,0,Wallet,Cancelled,2025-04-07,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,Ord1608,2025-02-17,Rahul,Rahul71@Gmail.Com,9789375429,Lucknow,Up,Mouse,Electronics,4,9999.0,0,Card,Returned,2025-02-27,39996.0,39996.0
520,Ord1609,2025-03-21,Rahul,Rahul99@Gmail.Com,9552649559,Mumbai,Maharashtra,Bottle,Home,2,1499.0,0,Wallet,Pending,2025-03-28,2998.0,2998.0
521,Ord1610,2025-04-10,Rohit,Rohit96@Gmail.Com,9700116928,Jaipur,Rajasthan,Mouse,Electronics,1,NaN,0,Netbanking,Delivered,2025-04-16,<NA>,<NA>
522,Ord1611,2025-01-11,Neha,Neha22@Gmail.Com,9580304152,Jaipur,Rajasthan,Chair,Furniture,3,999.0,0,Cod,Pending,2025-01-16,2997.0,2997.0
523,Ord1612,2025-03-03,Vikas,Vikas46@Gmail.Com,9551158398,Jaipur,Rajasthan,Shoes,Fashion,3,999.0,5,Cod,Cancelled,2025-03-09,2997.0,2847.15

In [1331]:
# Profit (Example- 20%)

df["Profit"]=df["Net_Amount"]*0.2

In [1332]:
df["Profit"]=df["Profit"].round(2)

In [1333]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Total_Sales,Net_Amount,Profit
0,Ord1002,2025-06-30,Neha,Neha82@Gmail.Com,9829008196,Delhi,Delhi,Chair,Furniture,4,1999.0,0,Upi,Pending,2025-07-03,7996.0,7996.0,1599.2
1,Ord1003,2025-02-03,Rohit,Rohit45@Gmail.Com,9280491167,Pune,Maharashtra,Watch,Fashion,5,4999.0,20,Card,Pending,2025-02-09,24995.0,19996.0,3999.2
2,Ord1004,2025-05-06,Amit,Amit6@Gmail.Com,9943310925,Jaipur,Rajasthan,Mouse,Electronics,3,1999.0,5,Cod,Returned,2025-05-08,5997.0,5697.15,1139.43
3,Ord1005,2025-01-20,Vikas,Vikas51@Gmail.Com,9495120474,Bengaluru,Karnataka,Laptop,Electronics,0,NaN,15,Wallet,Pending,2025-01-27,<NA>,<NA>,<NA>
4,Ord1006,2025-04-02,Rohit,Rohit71@Gmail.Com,9237331620,Pune,Maharashtra,Bottle,Home,0,1999.0,0,Wallet,Cancelled,2025-04-07,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,Ord1608,2025-02-17,Rahul,Rahul71@Gmail.Com,9789375429,Lucknow,Up,Mouse,Electronics,4,9999.0,0,Card,Returned,2025-02-27,39996.0,39996.0,7999.2
520,Ord1609,2025-03-21,Rahul,Rahul99@Gmail.Com,9552649559,Mumbai,Maharashtra,Bottle,Home,2,1499.0,0,Wallet,Pending,2025-03-28,2998.0,2998.0,599.6
521,Ord1610,2025-04-10,Rohit,Rohit96@Gmail.Com,9700116928,Jaipur,Rajasthan,Mouse,Electronics,1,NaN,0,Netbanking,Delivered,2025-04-16,<NA>,<NA>,<NA>
522,Ord1611,2025-01-11,Neha,Neha22@Gmail.Com,9580304152,Jaipur,Rajasthan,Chair,Furniture,3,999.0,0,Cod,Pending,2025-01-16,2997.0,2997.0,599.4
523,Ord1612,2025-03-03,Vikas,Vikas46@Gmail.Com,9551158398,Jaipur,Rajasthan,Shoes,Fashion,3,999.0,5,Cod,Cancelled,2025-03-09,2997.0,2847.15,569.43

In [1334]:
# Order Month

df["Order_Month"]=df["Order_Date"].dt.month_name()

In [1335]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Total_Sales,Net_Amount,Profit,Order_Month
0,Ord1002,2025-06-30,Neha,Neha82@Gmail.Com,9829008196,Delhi,Delhi,Chair,Furniture,4,1999.0,0,Upi,Pending,2025-07-03,7996.0,7996.0,1599.2,June
1,Ord1003,2025-02-03,Rohit,Rohit45@Gmail.Com,9280491167,Pune,Maharashtra,Watch,Fashion,5,4999.0,20,Card,Pending,2025-02-09,24995.0,19996.0,3999.2,February
2,Ord1004,2025-05-06,Amit,Amit6@Gmail.Com,9943310925,Jaipur,Rajasthan,Mouse,Electronics,3,1999.0,5,Cod,Returned,2025-05-08,5997.0,5697.15,1139.43,May
3,Ord1005,2025-01-20,Vikas,Vikas51@Gmail.Com,9495120474,Bengaluru,Karnataka,Laptop,Electronics,0,NaN,15,Wallet,Pending,2025-01-27,<NA>,<NA>,<NA>,January
4,Ord1006,2025-04-02,Rohit,Rohit71@Gmail.Com,9237331620,Pune,Maharashtra,Bottle,Home,0,1999.0,0,Wallet,Cancelled,2025-04-07,0.0,0.0,0.0,April
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,Ord1608,2025-02-17,Rahul,Rahul71@Gmail.Com,9789375429,Lucknow,Up,Mouse,Electronics,4,9999.0,0,Card,Returned,2025-02-27,39996.0,39996.0,7999.2,February
520,Ord1609,2025-03-21,Rahul,Rahul99@Gmail.Com,9552649559,Mumbai,Maharashtra,Bottle,Home,2,1499.0,0,Wallet,Pending,2025-03-28,2998.0,2998.0,599.6,March
521,Ord1610,2025-04-10,Rohit,Rohit96@Gmail.Com,9700116928,Jaipur,Rajasthan,Mouse,Electronics,1,NaN,0,Netbanking,Delivered,2025-04-16,<NA>,<NA>,<NA>,April
522,Ord1611,2025-01-11,Neha,Neha22@Gmail.Com,9580304152,Jaipur,Rajasthan,Chair,Furniture,3,999.0,0,Cod,Pending,2025-01-16,2997.0,2997.0,599.4,January
523,Ord1612,2025-03-03,Vikas,Vikas46@Gmail.Com,9551158398,Jaipur,Rajasthan,Shoes,Fashion,3,999.0,5,Cod,Cancelled,2025-03-09,2997.0,2847.15,569.43,March

In [1336]:
# Order Year

df["Order_Year"]=df["Order_Date"].dt.year

In [1337]:
df["Order_Year"].dtype

dtype('float64')

In [1338]:
df["Order_Year"]=df["Order_Year"].astype("Int64")

In [1339]:
df["Order_Year"]=df["Order_Year"].astype("str")

In [1340]:
df["Order_Year"].dtype

In [1341]:
df["Order_Year"].isnull().sum()

np.int64(12)

In [1342]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Total_Sales,Net_Amount,Profit,Order_Month,Order_Year
0,Ord1002,2025-06-30,Neha,Neha82@Gmail.Com,9829008196,Delhi,Delhi,Chair,Furniture,4,1999.0,0,Upi,Pending,2025-07-03,7996.0,7996.0,1599.2,June,2025
1,Ord1003,2025-02-03,Rohit,Rohit45@Gmail.Com,9280491167,Pune,Maharashtra,Watch,Fashion,5,4999.0,20,Card,Pending,2025-02-09,24995.0,19996.0,3999.2,February,2025
2,Ord1004,2025-05-06,Amit,Amit6@Gmail.Com,9943310925,Jaipur,Rajasthan,Mouse,Electronics,3,1999.0,5,Cod,Returned,2025-05-08,5997.0,5697.15,1139.43,May,2025
3,Ord1005,2025-01-20,Vikas,Vikas51@Gmail.Com,9495120474,Bengaluru,Karnataka,Laptop,Electronics,0,NaN,15,Wallet,Pending,2025-01-27,<NA>,<NA>,<NA>,January,2025
4,Ord1006,2025-04-02,Rohit,Rohit71@Gmail.Com,9237331620,Pune,Maharashtra,Bottle,Home,0,1999.0,0,Wallet,Cancelled,2025-04-07,0.0,0.0,0.0,April,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,Ord1608,2025-02-17,Rahul,Rahul71@Gmail.Com,9789375429,Lucknow,Up,Mouse,Electronics,4,9999.0,0,Card,Returned,2025-02-27,39996.0,39996.0,7999.2,February,2025
520,Ord1609,2025-03-21,Rahul,Rahul99@Gmail.Com,9552649559,Mumbai,Maharashtra,Bottle,Home,2,1499.0,0,Wallet,Pending,2025-03-28,2998.0,2998.0,599.6,March,2025
521,Ord1610,2025-04-10,Rohit,Rohit96@Gmail.Com,9700116928,Jaipur,Rajasthan,Mouse,Electronics,1,NaN,0,Netbanking,Delivered,2025-04-16,<NA>,<NA>,<NA>,April,2025
522,Ord1611,2025-01-11,Neha,Neha22@Gmail.Com,9580304152,Jaipur,Rajasthan,Chair,Furniture,3,999.0,0,Cod,Pending,2025-01-16,2997.0,2997.0,599.4,January,2025
523,Ord1612,2025-03-03,Vikas,Vikas46@Gmail.Com,9551158398,Jaipur,Rajasthan,Shoes,Fashion,3,999.0,5,Cod,Cancelled,2025-03-09,2997.0,2847.15,569.43,March,2025

In [1343]:
# WeekDay

df["WeekDay"]=df["Order_Date"].dt.day_name()

In [1344]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,...,Discount,Payment_Mode,Order_Status,Delivery_Date,Total_Sales,Net_Amount,Profit,Order_Month,Order_Year,WeekDay
0,Ord1002,2025-06-30,Neha,Neha82@Gmail.Com,9829008196,Delhi,Delhi,Chair,Furniture,4,...,0,Upi,Pending,2025-07-03,7996.0,7996.0,1599.2,June,2025,Monday
1,Ord1003,2025-02-03,Rohit,Rohit45@Gmail.Com,9280491167,Pune,Maharashtra,Watch,Fashion,5,...,20,Card,Pending,2025-02-09,24995.0,19996.0,3999.2,February,2025,Monday
2,Ord1004,2025-05-06,Amit,Amit6@Gmail.Com,9943310925,Jaipur,Rajasthan,Mouse,Electronics,3,...,5,Cod,Returned,2025-05-08,5997.0,5697.15,1139.43,May,2025,Tuesday
3,Ord1005,2025-01-20,Vikas,Vikas51@Gmail.Com,9495120474,Bengaluru,Karnataka,Laptop,Electronics,0,...,15,Wallet,Pending,2025-01-27,<NA>,<NA>,<NA>,January,2025,Monday
4,Ord1006,2025-04-02,Rohit,Rohit71@Gmail.Com,9237331620,Pune,Maharashtra,Bottle,Home,0,...,0,Wallet,Cancelled,2025-04-07,0.0,0.0,0.0,April,2025,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,Ord1608,2025-02-17,Rahul,Rahul71@Gmail.Com,9789375429,Lucknow,Up,Mouse,Electronics,4,...,0,Card,Returned,2025-02-27,39996.0,39996.0,7999.2,February,2025,Monday
520,Ord1609,2025-03-21,Rahul,Rahul99@Gmail.Com,9552649559,Mumbai,Maharashtra,Bottle,Home,2,...,0,Wallet,Pending,2025-03-28,2998.0,2998.0,599.6,March,2025,Friday
521,Ord1610,2025-04-10,Rohit,Rohit96@Gmail.Com,9700116928,Jaipur,Rajasthan,Mouse,Electronics,1,...,0,Netbanking,Delivered,2025-04-16,<NA>,<NA>,<NA>,April,2025,Thursday
522,Ord1611,2025-01-11,Neha,Neha22@Gmail.Com,9580304152,Jaipur,Rajasthan,Chair,Furniture,3,...,0,Cod,Pending,2025-01-16,2997.0,2997.0,599.4,January,2025,Saturday
523,Ord1612,2025-03-03,Vikas,Vikas46@Gmail.Com,9551158398,Jaipur,Rajasthan,Shoes,Fashion,3,...,5,Cod,Cancelled,2025-03-09,2997.0,2847.15,569.43,March,2025,Monday

In [1345]:
col=["Order_Month", "Order_Year", "WeekDay"]
for c in col:
    df[c]=df[c].fillna("Unknown")

In [1346]:
df["Order_Year"].isnull().sum()

np.int64(0)

In [1347]:
# Final Data validation checking

df.info()

<class 'pandas.DataFrame'>
Index: 444 entries, 0 to 523
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       444 non-null    str
 1   Order_Date     432 non-null    datetime64[us]
 2   Customer_Name  444 non-null    str
 3   Email          444 non-null    str
 4   Phone          444 non-null    string
 5   City           444 non-null    str
 6   State          444 non-null    str
 7   Product        444 non-null    str
 8   Category       444 non-null    str
 9   Qty            444 non-null    Int64
 10  Unit_Price     398 non-null    float64
 11  Discount       444 non-null    Int64
 12  Payment_Mode   444 non-null    str
 13  Order_Status   444 non-null    str
 14  Delivery_Date  442 non-null    datetime64[us]
 15  Total_Sales    398 non-null    Float64
 16  Net_Amount     398 non-null    Float64
 17  Profit         398 non-null    Float64
 18  Order_Month    444 non-null    str
 19  Order_Year     444 non-null    str
 20  WeekDay        444 non-null    str
dtypes: Float64(3), Int64(2), datetime64[us](2), float64(1), str(12), string(1)
memory usage: 78.5 KB

In [1348]:
df.isnull().sum()

Order_ID          0
Order_Date       12
Customer_Name     0
Email             0
Phone             0
City              0
State             0
Product           0
Category          0
Qty               0
Unit_Price       46
Discount          0
Payment_Mode      0
Order_Status      0
Delivery_Date     2
Total_Sales      46
Net_Amount       46
Profit           46
Order_Month       0
Order_Year        0
WeekDay           0
dtype: int64

In [1349]:
df.replace(['N/A', 'NULL', ''], np.nan, inplace=True)

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,...,Discount,Payment_Mode,Order_Status,Delivery_Date,Total_Sales,Net_Amount,Profit,Order_Month,Order_Year,WeekDay
0,Ord1002,2025-06-30,Neha,Neha82@Gmail.Com,9829008196,Delhi,Delhi,Chair,Furniture,4,...,0,Upi,Pending,2025-07-03,7996.0,7996.0,1599.2,June,2025,Monday
1,Ord1003,2025-02-03,Rohit,Rohit45@Gmail.Com,9280491167,Pune,Maharashtra,Watch,Fashion,5,...,20,Card,Pending,2025-02-09,24995.0,19996.0,3999.2,February,2025,Monday
2,Ord1004,2025-05-06,Amit,Amit6@Gmail.Com,9943310925,Jaipur,Rajasthan,Mouse,Electronics,3,...,5,Cod,Returned,2025-05-08,5997.0,5697.15,1139.43,May,2025,Tuesday
3,Ord1005,2025-01-20,Vikas,Vikas51@Gmail.Com,9495120474,Bengaluru,Karnataka,Laptop,Electronics,0,...,15,Wallet,Pending,2025-01-27,<NA>,<NA>,<NA>,January,2025,Monday
4,Ord1006,2025-04-02,Rohit,Rohit71@Gmail.Com,9237331620,Pune,Maharashtra,Bottle,Home,0,...,0,Wallet,Cancelled,2025-04-07,0.0,0.0,0.0,April,2025,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,Ord1608,2025-02-17,Rahul,Rahul71@Gmail.Com,9789375429,Lucknow,Up,Mouse,Electronics,4,...,0,Card,Returned,2025-02-27,39996.0,39996.0,7999.2,February,2025,Monday
520,Ord1609,2025-03-21,Rahul,Rahul99@Gmail.Com,9552649559,Mumbai,Maharashtra,Bottle,Home,2,...,0,Wallet,Pending,2025-03-28,2998.0,2998.0,599.6,March,2025,Friday
521,Ord1610,2025-04-10,Rohit,Rohit96@Gmail.Com,9700116928,Jaipur,Rajasthan,Mouse,Electronics,1,...,0,Netbanking,Delivered,2025-04-16,<NA>,<NA>,<NA>,April,2025,Thursday
522,Ord1611,2025-01-11,Neha,Neha22@Gmail.Com,9580304152,Jaipur,Rajasthan,Chair,Furniture,3,...,0,Cod,Pending,2025-01-16,2997.0,2997.0,599.4,January,2025,Saturday
523,Ord1612,2025-03-03,Vikas,Vikas46@Gmail.Com,9551158398,Jaipur,Rajasthan,Shoes,Fashion,3,...,5,Cod,Cancelled,2025-03-09,2997.0,2847.15,569.43,March,2025,Monday

In [1350]:
df.shape

(444, 21)

In [1351]:
df.isnull().sum()

Order_ID          6
Order_Date       12
Customer_Name     0
Email             0
Phone             0
City              0
State             0
Product           0
Category          0
Qty               0
Unit_Price       46
Discount          0
Payment_Mode      0
Order_Status      0
Delivery_Date     2
Total_Sales      46
Net_Amount       46
Profit           46
Order_Month       0
Order_Year        0
WeekDay           0
dtype: int64

In [1352]:
df.info()

<class 'pandas.DataFrame'>
Index: 444 entries, 0 to 523
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       438 non-null    str
 1   Order_Date     432 non-null    datetime64[us]
 2   Customer_Name  444 non-null    str
 3   Email          444 non-null    str
 4   Phone          444 non-null    string
 5   City           444 non-null    str
 6   State          444 non-null    str
 7   Product        444 non-null    str
 8   Category       444 non-null    str
 9   Qty            444 non-null    Int64
 10  Unit_Price     398 non-null    float64
 11  Discount       444 non-null    Int64
 12  Payment_Mode   444 non-null    str
 13  Order_Status   444 non-null    str
 14  Delivery_Date  442 non-null    datetime64[us]
 15  Total_Sales    398 non-null    Float64
 16  Net_Amount     398 non-null    Float64
 17  Profit         398 non-null    Float64
 18  Order_Month    444 non-null    str
 19  Order_Year     444 non-null    str
 20  WeekDay        444 non-null    str
dtypes: Float64(3), Int64(2), datetime64[us](2), float64(1), str(12), string(1)
memory usage: 78.5 KB

In [1353]:
# Clean csv Export

df.to_csv("Clean_Ecommerce_Project.csv",index=False)

# Load Data into SQL

In [1354]:
# Loading Data into SQL

import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [1355]:
df=pd.read_csv("Clean_Ecommerce_Project.csv")

In [1356]:
engine=create_engine("mysql+pymysql://root:Sunny%402838@localhost:3306/Ecommerce")

In [1357]:
df.to_sql(name="ecommerce_data", con=engine, if_exists="replace", index=False)

444